### PR TITLE
Fixed bash-isms in entrypoint run by /bin/sh

### LINKED ISSUE #26: remote_branch variable is not correctly detected
I am running this action on a repository like `organization/organization.github.io`
When running the action in a pull request, the consequences of this code snippet are potentially destructive

https://github.com/helaili/jekyll-action/blob/af3293c2d6f25c063e2a3448433fe47d4d65b11c/entrypoint.sh#L30-L35

In my repository, the script tried to push to `gh-pages` branch even if it should not
You may need to add a caveat in the documentation

### PR DESCRIPTION
**Pull request by r4zzz4k**
`[[` is a feature of `bash`, and `entrypoint.sh` has `sh` in it's shebang. So the script dumps warning `[[: not found` somewhere and goes with wrong branch. Same goes for other tests in the script.

IIRC, Alpine doesn't have bash bundled, so simple change of shebang won't help. I suggest removing bash-specific syntax and keep with clean POSIX sh. I'm not a shell guru, so substring check for repo name can be probably done better, this is the first thing I came up with based on suffix removing via `${parameter%word}` described [here](https://pubs.opengroup.org/onlinepubs/007908775/xcu/chap2.html#tag_001_006_002).

Fixes #26.

For the record: [here's the build](https://github.com/inkremental/inkremental.github.io/runs/644514419?check_suite_focus=true#step:5:127) with current master, and here's [another one with this PR](https://github.com/inkremental/inkremental.github.io/runs/644645875?check_suite_focus=true#step:5:62). Note the lines
`Publishing to inkremental/inkremental.github.io on branch gh-pages`
and
`Publishing to inkremental/inkremental.github.io on branch master`
correspondingly.

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -8,10 +8,10 @@ bundle config path vendor/bundle
 bundle install
 echo "::debug ::Completed bundle install"
 
-if [[ ${INPUT_JEKYLL_SRC} ]]; then
+if [ "x${INPUT_JEKYLL_SRC}" != "x" ]; then
```
Comment (helaili) [inline entrypoint.sh:11]:
```suggestion
if [ -n ${INPUT_JEKYLL_SRC}"  ]; then
```

File: entrypoint.sh [hunk 2]
```diff
@@ -8,10 +8,10 @@ bundle config path vendor/bundle
...
   JEKYLL_SRC=${INPUT_JEKYLL_SRC}
   echo "::debug ::Using parameter value ${JEKYLL_SRC} as a source directory"
-elif [[ ${SRC} ]]; then
+elif [ "x${SRC}" != "x" ]; then
```
Comment (helaili) [inline entrypoint.sh:14]:
```suggestion
elif [ -n "${SRC}" ]; then
```

File: entrypoint.sh [hunk 3]
```diff
@@ -28,13 +28,13 @@ cd build
 touch .nojekyll
 
 # Is this a regular repo or an org.github.io type of repo
-if [[ "${GITHUB_REPOSITORY}" == *".github.io"* ]]; then
+if [ "x${GITHUB_REPOSITORY%.github.io}" != "x$GITHUB_REPOSITORY" ]; then
   remote_branch="master"
 else
   remote_branch="gh-pages"
 fi
```
Comment (helaili) [inline entrypoint.sh:35]:
```suggestion
case "${GITHUB_REPOSITORY}" in
  *.github.io) remote_branch="master"  ;;
  *) remote_branch="gh-pages" ;;
esac
```

**Comment by r4zzz4k** [comment]
Sure, I didn't actually check if dash has `test` as a built-in in a same way modern shells do. Seems that `[ -n` should be perfectly safe.
I've also didn't expect `case` to match `*` anywhere but in the end of the pattern.
Thanks for suggestions!
